-- STEP-005: Share / Hisse lifecycle, ownership & acquisition foundation
-- (docs/04 Share section + docs/16 candidate lifecycle + STEP-005).
--
-- A Share is a first-class durable business asset — never a
-- shareholder.share_count or a balance. Every Share has a stable,
-- human-readable share_number generated by a PostgreSQL identity
-- column (concurrency-safe by construction; no MAX+1 race).
--
-- Ownership is TEMPORAL (share_ownerships): at most one active owner
-- (ended_at IS NULL) and non-overlapping intervals, enforced by a
-- PostgreSQL exclusion constraint (btree_gist, established in 0004).
-- Every ownership interval references the share_events row that opened
-- it, so "how did this ownership begin?" is always answerable.
--
-- FINANCIAL BOUNDARY: amount/currency on share_events record only the
-- agreed business value (acquisition fee, sale price). NULL means "not
-- specified"; 0 means "explicitly zero" — the distinction is preserved.
-- No Payment/Cashbox/Ledger state is created by Share events (STEP-005
-- §18–§19; docs/04: "a private sale price is not automatically a
-- cooperative Financial Account movement").

CREATE TABLE shares (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    -- Business identifier: stable across transfers/sales/status changes,
    -- generated by the database identity sequence (§9/§10).
    share_number BIGINT GENERATED ALWAYS AS IDENTITY,
    -- Lifecycle subset of docs/16 implemented now: active ↔ suspended;
    --   voided = terminal mistaken-record correction (never hard delete).
    --   return-pending/closed belong to the future Share Return workflow.
    status       TEXT NOT NULL DEFAULT 'active'
                 CONSTRAINT shares_status_check
                 CHECK (status IN ('active', 'suspended', 'voided')),
    created_by   UUID REFERENCES users (id),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX shares_share_number_key ON shares (share_number);

-- Business history (§27/§53): append-oriented domain events, distinct
-- from the security_events audit trail. No UPDATE/DELETE product path
-- exists; corrections are future reversal/correction events (docs/19).
CREATE TABLE share_events (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    share_id            UUID NOT NULL REFERENCES shares (id),
    event_type          TEXT NOT NULL
                        CONSTRAINT share_events_type_check CHECK (
                            event_type IN (
                                'initial_acquisition',
                                'transfer',
                                'sale',
                                'status_change',
                                'voided')),
    occurred_at         TIMESTAMPTZ NOT NULL,
    from_shareholder_id UUID REFERENCES shareholders (id),
    to_shareholder_id   UUID REFERENCES shareholders (id),
    -- Only meaningful on initial_acquisition: founder | later_acquisition.
    acquisition_type    TEXT
                        CONSTRAINT share_events_acquisition_check CHECK (
                            acquisition_type IN ('founder', 'later_acquisition')),
    -- Agreed business value ONLY (acquisition fee / sale price).
    -- Exact money per ADR-004: NUMERIC, never float. NULL = not
    -- specified; 0 = explicitly zero (§17).
    amount              NUMERIC(19, 2)
                        CONSTRAINT share_events_amount_nonneg
                        CHECK (amount IS NULL OR amount >= 0),
    currency            TEXT NOT NULL DEFAULT 'TRY'
                        CONSTRAINT share_events_currency_check
                        CHECK (currency = 'TRY'),
    -- Status-change provenance (status_change/voided events only).
    status_from         TEXT,
    status_to           TEXT,
    reason              TEXT,
    actor_user_id       UUID NOT NULL REFERENCES users (id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX share_events_share_chronology_idx
    ON share_events (share_id, occurred_at, id);

-- Temporal ownership (§11): at most one active owner per Share;
-- historical intervals never overlap. Transfer/sale close the current
-- interval and open the new one inside ONE transaction.
CREATE TABLE share_ownerships (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    share_id        UUID NOT NULL REFERENCES shares (id),
    shareholder_id  UUID NOT NULL REFERENCES shareholders (id),
    started_at      TIMESTAMPTZ NOT NULL,
    ended_at        TIMESTAMPTZ,
    -- How this interval began: 'founder' | 'later_acquisition' for the
    -- initial allocation, 'transfer' | 'sale' for later owner changes.
    acquisition_type TEXT NOT NULL
                    CONSTRAINT share_ownerships_acquisition_check CHECK (
                        acquisition_type IN (
                            'founder', 'later_acquisition',
                            'transfer', 'sale')),
    -- The business event that opened this interval (provenance).
    source_event_id UUID NOT NULL REFERENCES share_events (id),
    created_by      UUID NOT NULL REFERENCES users (id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT share_ownerships_interval_check
      CHECK (ended_at IS NULL OR ended_at >= started_at)
);

ALTER TABLE share_ownerships
    ADD CONSTRAINT share_ownerships_no_overlap
    EXCLUDE USING gist (
        share_id WITH =,
        tstzrange(started_at, COALESCE(ended_at, 'infinity'::timestamptz)) WITH &&
    );

CREATE INDEX share_ownerships_shareholder_current_idx
    ON share_ownerships (shareholder_id)
    WHERE ended_at IS NULL;

CREATE INDEX share_ownerships_share_current_idx
    ON share_ownerships (share_id)
    WHERE ended_at IS NULL;

-- STEP-005 permission catalog additions (application-owned keys).
INSERT INTO permissions (key, name, description, category) VALUES
    ('shares.read',
     'Hisseleri Görüntüle',
     'Hisse kayıtlarını, sahiplik bilgisini ve hareket geçmişini görüntüleyebilir.',
     'Hisse Yönetimi'),
    ('shares.manage',
     'Hisseleri Yönet',
     'Hisse tahsis edebilir, devir/satış işlemi yapabilir ve durumunu değiştirebilir.',
     'Hisse Yönetimi');

-- Explicit migration-time grant to the system-seeded administrative
-- role (fixed id). No wildcard inheritance; custom roles untouched.
INSERT INTO role_permissions (role_id, permission_id)
SELECT
    '00000000-0000-4000-8000-000000000001',
    p.id
FROM permissions p
WHERE p.key IN ('shares.read', 'shares.manage')
ON CONFLICT DO NOTHING;

-- No Payment/Cashbox/Bank/Ledger/Debt/Period objects: future STEPs own
-- them. Share events record business conditions only.
