-- STEP-006: Period / Dönem, Assessment Rule / Tahakkuk Kuralı and
-- Assessment / Tahakkuk (obligation) foundation (docs/05, docs/16,
-- docs/17 POLICY_DRIVEN note + STEP-006 §8–§47).
--
-- A Period is a first-class business entity with a stable
-- database-generated business number (period_number, IDENTITY —
-- concurrency-safe, never MAX+1). Business dates are DATE columns so
-- Türkiye business dates never shift under UTC conversion (§11).
--
-- An Assessment is a DURABLE obligation record — never computed
-- dynamically from current state (§18/§19/§35). Once generated, a
-- Share transfer/sale, Family move, Guardian change or name edit can
-- NEVER rewrite it; corrections are deferred to an explicit
-- reversal/correction workflow (docs/19).
--
-- The governing rule is explicit and durable (§13–§16): exactly one
-- rule row per Period (docs/05 defines "a payable amount/rule" per
-- Period; multiple-rules-per-Period are intentionally NOT modeled).
-- Rule rows are editable while the Period is `draft` and immutable
-- once `open` (§37).
--
-- FINANCIAL BOUNDARY: an Assessment is an obligation (tahakkuk), not a
-- settlement. This migration creates NO Payment/Cashbox/Bank/Ledger/
-- Allocation/Receipt state and no paid/remaining fields (§42–§44).
-- STEP-007 allocates real payments against the durable assessment ids.

CREATE TABLE periods (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    -- Business identifier: stable, human-readable, generated by the
    -- database identity sequence (§9/§10).
    period_number   BIGINT GENERATED ALWAYS AS IDENTITY,
    name            TEXT NOT NULL
                    CONSTRAINT periods_name_nonempty CHECK (btrim(name) <> ''),
    -- Lifecycle (docs/16 candidate Draft → Open → Closed/Locked):
    --   draft  — configuration editable, no obligations exist;
    --   open   — assessments generated durably (finalize command);
    --   closed — locked for ordinary mutation (explicit close command).
    status          TEXT NOT NULL DEFAULT 'draft'
                    CONSTRAINT periods_status_check
                    CHECK (status IN ('draft', 'open', 'closed')),
    collection_start_date DATE NOT NULL,
    due_date        DATE NOT NULL,
    created_by      UUID REFERENCES users (id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT periods_dates_check
      CHECK (due_date >= collection_start_date)
);

CREATE UNIQUE INDEX periods_period_number_key ON periods (period_number);

-- The explicit, durable generation rule (§13). Exactly one rule per
-- Period (UNIQUE period_id). The assessment_effective_date is the
-- business date whose share-ownership state PER_SHARE generation
-- resolves against — explicit, never a silent NOW() (§27).
CREATE TABLE assessment_rules (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    period_id       UUID NOT NULL UNIQUE REFERENCES periods (id),
    -- 'per_shareholder': one obligation per eligible Shareholder
    --   (share count does not affect the amount, §14);
    -- 'per_share':     one amount component per eligible Share owned at
    --   the effective date (§15).
    rule_type       TEXT NOT NULL
                    CONSTRAINT assessment_rules_type_check
                    CHECK (rule_type IN ('per_shareholder', 'per_share')),
    -- Exact money per ADR-004. Zero is rejected: a zero-value rule
    -- would create meaningless obligations (§41 documents the choice).
    base_amount     NUMERIC(19, 2) NOT NULL
                    CONSTRAINT assessment_rules_amount_positive
                    CHECK (base_amount > 0),
    currency        TEXT NOT NULL DEFAULT 'TRY'
                    CONSTRAINT assessment_rules_currency_check
                    CHECK (currency = 'TRY'),
    assessment_effective_date DATE NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Durable obligation per (Period, Shareholder). rule_type/base_amount/
-- currency/effective date are SNAPSHOTS of the governing rule at
-- generation time (§35/§36) so the row stays explainable even if the
-- draft rule record were ever changed — post-finalization rules are
-- immutable anyway (§37). UNIQUE(period_id, shareholder_id) makes
-- double generation impossible at the database level (§32/§33).
CREATE TABLE assessments (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    period_id       UUID NOT NULL REFERENCES periods (id),
    -- The DEBTOR is always the Shareholder. Family is never the debtor
    -- (§46–§48); generation-time family context stays derivable through
    -- temporal shareholder_family_memberships (§78).
    shareholder_id  UUID NOT NULL REFERENCES shareholders (id),
    rule_type       TEXT NOT NULL
                    CONSTRAINT assessments_rule_type_check
                    CHECK (rule_type IN ('per_shareholder', 'per_share')),
    base_amount     NUMERIC(19, 2) NOT NULL,
    amount          NUMERIC(19, 2) NOT NULL
                    CONSTRAINT assessments_amount_nonneg CHECK (amount >= 0),
    currency        TEXT NOT NULL
                    CONSTRAINT assessments_currency_check CHECK (currency = 'TRY'),
    -- Minimal lifecycle (§57): 'active' is the only value generated
    -- today; 'voided' is reserved for the future correction/reversal
    -- workflow (docs/19). NO paid/partially_paid/overdue states —
    -- settlement tracking begins with the Payment module.
    status          TEXT NOT NULL DEFAULT 'active'
                    CONSTRAINT assessments_status_check
                    CHECK (status IN ('active', 'voided')),
    assessment_effective_date DATE NOT NULL,
    generated_by    UUID NOT NULL REFERENCES users (id),
    generated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT assessments_period_shareholder_key
      UNIQUE (period_id, shareholder_id)
);

CREATE INDEX assessments_shareholder_idx ON assessments (shareholder_id);

-- Per-Share provenance for 'per_share' assessments (§23, docs/05
-- core business rule, docs/15: "independently traceable assessment
-- for every eligible Share"). Each row answers "which Share caused
-- how much of this obligation?". ownership_id pins the exact temporal
-- share_ownerships interval used, so the record stays explainable
-- after later transfers. 'per_shareholder' assessments have no rows
-- here — their source is the Shareholder's eligibility itself (§24).
CREATE TABLE assessment_share_sources (
    assessment_id   UUID NOT NULL REFERENCES assessments (id),
    share_id        UUID NOT NULL REFERENCES shares (id),
    ownership_id    UUID NOT NULL REFERENCES share_ownerships (id),
    amount_component NUMERIC(19, 2) NOT NULL
                    CONSTRAINT assessment_sources_component_positive
                    CHECK (amount_component > 0),
    PRIMARY KEY (assessment_id, share_id)
);

CREATE INDEX assessment_share_sources_share_idx
    ON assessment_share_sources (share_id);

-- STEP-006 permission catalog additions (application-owned keys, §50).
INSERT INTO permissions (key, name, description, category) VALUES
    ('periods.read',
     'Dönemleri Görüntüle',
     'Dönem kayıtlarını, tahakkuk kurallarını ve özetlerini görüntüleyebilir.',
     'Dönem Yönetimi'),
    ('periods.manage',
     'Dönemleri Yönet',
     'Taslak dönem oluşturabilir, düzenleyebilir, silebilir ve dönemi kapatabilir.',
     'Dönem Yönetimi'),
    ('assessments.read',
     'Tahakkukları Görüntüle',
     'Tahakkuk listelerini, kaynak hisseleri ve tahakkuk önizlemesini görüntüleyebilir.',
     'Dönem Yönetimi'),
    ('assessments.manage',
     'Tahakkukları Yönet',
     'Tahakkuk önizlemesi çalıştırabilir ve dönem tahakkuklarını kesin olarak oluşturabilir.',
     'Dönem Yönetimi');

-- Explicit migration-time grant to the system-seeded administrative
-- role (fixed id). No wildcard inheritance; custom roles untouched.
INSERT INTO role_permissions (role_id, permission_id)
SELECT
    '00000000-0000-4000-8000-000000000001',
    p.id
FROM permissions p
WHERE p.key IN ('periods.read', 'periods.manage',
                'assessments.read', 'assessments.manage')
ON CONFLICT DO NOTHING;

-- No Payment/Collection/Cashbox/Bank/Ledger/Receipt/Allocation or
-- Social Aid objects: later STEPs own them (§3, §49).
